### ISSUE TITLE
Compassview is constantly rotating

### ISSUE THREAD

**Issue by DevCCC** [kvirair/Compass-View-Library#4]
Hi! @jrocharodrigues this is good tutorial and its usefull for me.
But the main problem with this is the compassview is constantly rotating infinitely 
Please guide me for that.

**Comment by jrocharodrigues** [comment]
Hi,

I never got into that issue... 

Maybe try to calibrate your compass and check if the issue disappears.
Anyway i'm not the creator of the library, so maybe @kvirair is a better help than me.

**Comment by kvirair** [comment]
Hi,

Please, write me your device model, android os, and i check :)

**Comment by DevCCC** [comment]
Samsung Duos Quattro : 4.1.2

**Comment by kvirair** [comment]
@DevCCC, i fix this issue in saturday, okay? You don't hurry? :)

**Comment by DevCCC** [comment]
okay  
thanks :-), bro...!!!

**Comment by kvirair** [comment]
I check in latest library version (not .jar), it's all okay there, may you make a video? Or send me logs, i recently added them in project. :)

Also, don't forget rotate phone in all directions, for sensors calibration.
